homeassistant:
  name: Lintulahti
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 50
  unit_system: metric
  time_zone: Europe/Helsinki
  customize: !include customize.yaml

updater:
# discovery:
history:
logbook:
sun:
frontend:
emulated_hue:
  host_ip: 192.168.1.33
  listen_port: 8300
  type: alexa
logger:
  default: debug
  logs:
    homeassistant.components.api: info
    homeassistant.components.http: critical

group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
automation: !include_dir_list automations
switch: !include switches.yaml

media_player:
  - platform: yamaha
    host: 192.168.1.111

light:
  - platform: houmio
    sitekey: !secret sitekey

device_tracker:
  - platform: locative
    track_new_devices: False
  - platform: asuswrt
    track_new_devices: False
    host: 192.168.1.1
    username: admin
    password: !secret asuspw

http:
  api_password: !secret apipw
  trusted_networks:
    - 192.168.0.0/24

sensor:
  - platform: plex
    host: 192.168.1.116
    username: !secret plexuser
    password: !secret plexpw

shell_command:
  tv_off: echo "standby 0" | cec-client -s -m
  tv_on: echo "on 0" | cec-client -s -m

tellduslive:
  public_key: !secret telldus_public_key
  private_key: !secret telldus_private_key
  token: !secret telldus_token
  token_secret: !secret telldus_token_secret

ios:
config:
