alias: 'Someone arrives to empty house'
trigger:
  - platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: light.eteinen
      state: 'off'
    - condition: sun
      after: sunset
      after_offset: "-1:00:00"
action:
  - service: homeassistant.turn_on
    entity_id: scene.arrival
  - condition: or
    conditions:
      - condition: time
        after: '10:00:00'
        before: '21:00:00'
  - service: switch.turn_on
    entity_id: switch.olohuone_audio
  - service: switch.turn_on
    entity_id: switch.vahvistin_sauna
  - service: switch.turn_on
    entity_id: switch.makuuhuone_pistoke
