alias: 'Someone arrives to empty house'
trigger:
  - platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
condition:
  condition: state
  entity_id: light.eteinen
  state: 'off'
action:
  service: homeassistant.turn_on
  entity_id: scene.arrival
