alias: 'Turn on balcony at sunset'
trigger:
  platform: sun
  event: sunset
condition:
  - condition: state
    entity_id: light.parveke
    state: 'off'
  - condition: state
    entity_id: group.all_devices
    state: 'home'
action:
  service: light.turn_on
  entity_id: light.parveke
